FROM node:20.17.0-alpine
WORKDIR /app
COPY public/ public/
COPY src/ src/
COPY vite.config.js .
COPY package.json .
COPY index.html .
# RUN npm install --legacy-peer-deps
RUN npm install --legacy-peer-deps
RUN npm run build
CMD ["npm", "run", "start"]
EXPOSE 3000